edition = "2023";

// The .proto file starts with a package declaration, 
// which helps to prevent naming conflicts between different projects. 
// In Python, packages are normally determined by directory structure, 
// so the package you define in your .proto file will have no effect on the generated code. 
// However, you should still declare one to avoid name collisions in the Protocol Buffers name space as well as in non-Python languages.
package tutorial;

// A message is just an aggregate containing a set of typed fields. 
message Person {
  // The " = 1", " = 2" markers on each element identify the unique “tag” 
  // that field uses in the binary encoding. 
  // Tag numbers 1-15 require one less byte to encode than higher numbers, 
  // so as an optimization you can decide to use those tags for the commonly used or repeated elements, 
  // leaving tags 16 and higher for less-commonly used optional elements. 
  // Each element in a repeated field requires re-encoding the tag number, 
  // so repeated fields are particularly good candidates for this optimization.
  string name = 1;
  int32 id = 2;
  string email = 3;

  enum PhoneType {
    PHONE_TYPE_UNSPECIFIED = 0;
    PHONE_TYPE_MOBILE = 1;
    PHONE_TYPE_HOME = 2;
    PHONE_TYPE_WORK = 3;
  }

  // You can even define message types nested inside other messages
  message PhoneNumber {
    string number = 1;
    PhoneType type = 2 [default = PHONE_TYPE_HOME];
  }

  repeated PhoneNumber phones = 4;
}

message AddressBook {
  repeated Person people = 1;
}

